# 03-deploy-writer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-writer
  namespace: demo-azurefile-smb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-writer
  template:
    metadata:
      labels:
        app: file-writer
    spec:
      containers:
        - name: writer
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "$(date) pod=${HOSTNAME} My name is ALok" >> /mnt/share/hello.txt
                sleep 2
              done
          volumeMounts:
            - name: share
              mountPath: /mnt/share
      volumes:
        - name: share
          persistentVolumeClaim:
            claimName: pvc-azurefile-smb

