apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-imagincloud
spec:
  acme:
    email: alokadhao@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-imagincloud
    solvers:
    - http01:
        ingress:
          class: nginx